version: "3.9"
services:
  wouldyou-bot:
    container_name: bot
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - node
    labels:
      gg.wouldyou.compose-author: "Discord username 536b656c6c79 "
networks:
  node:
    driver: bridge